# Generated by Django 4.2.1 on 2023-06-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_itvedant_delete_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="itvedant",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
